### ISSUE TITLE
Draft general website copy

### ISSUE THREAD

**Issue by felixhammerl** [pixelated/pixelated-project.github.io#32]

**Comment by re-nobre** [comment]
Hey, @felixhammerl 
I run your branch local in my machine and I would like to point some impressions:

- In my macbook, using chrome with a bookmarks bar the homepage is not only one page. It has a scroll bar but we don't have more content. Is possible that the homepage be responsive?

- The font size and the icons look too big and it isn't responsive. Is possible that the font size be responsive?

- For me, the heart and the question 'how can I help?' don't mean anything related with FAQ. For me, when I click on 'how can I help' I hope to find only the ways to contribute.

- I keep thinking that the FAQ is too long. Even the index of the FAQ is too long. :P What do you think about the idea of break it in other page with link on our navbar? I suggest  that we can have a page for the overview+architecture and an another page for contribute. What do you think?

**Comment by felixhammerl** [comment]
> In my macbook, using chrome with a bookmarks bar the homepage is not only one page. It has a scroll bar but we don't have more content. Is possible that the homepage be responsive?

Sorry, used the wrong box-sizing model. Fixed with https://github.com/pixelated/pixelated-project.github.io/commit/a86e536

> The font size and the icons look too big and it isn't responsive. Is possible that the font size be responsive?

It *is* responsive, breakpoints are based on the screen width. If you want them smaller, or bigger, we can do that via a couple of media queries...

> For me, the heart and the question 'how can I help?' don't mean anything related with FAQ. For me, when I click on 'how can I help' I hope to find only the ways to contribute.

Uhm ... that's what's happening now. I takes you to "Sounds good! How can I contribute?" in the FAQ, which gives you pointers to get started. What am I not seeing here?

Clicking on the "If you know (...)"-links takes you to the respective repos and issues to get you started.

> I keep thinking that the FAQ is too long. Even the index of the FAQ is too long. :P What do you think about the idea of break it in other page with link on our navbar? I suggest that we can have a page for the overview+architecture and an another page for contribute. What do you think?

No, the FAQ is not supposed to be read in one setting, but rather used by you to point users to certain paragraphs. It has to be long and extensive, because it's supposed to be the singular source of truth.

**Comment by pereiragislene** [comment]
I was playing around with the blog page and made some small modifications on the browser. What do you think?

<img width="1440" alt="screen shot 2016-01-29 at 16 36 07" src="https://cloud.githubusercontent.com/assets/554552/12686481/970dc2a6-c6a8-11e5-883c-3326bea0993d.png">

**Comment by albogabriel** [comment]
Some of my perceptions:

1. The hive background for the home page doesn't provide enough contrast with the text. Some ways to improve that would be:
a) Change the background. We can make the hive more transparent so the background for the text is a bit more solid, for instance. We could also remove the hive background altogether, but I personally think it's cool to leave it there to repeat the logo.
b) Make the text - especially the three clickable items - white instead of grey. 

2. The three clickable items could call for action more clearly. One possibility is to have them stand out by having them framed/surrounded with a solid background - say, round. 

3. The letter icon is in a different style when compared to other icons we use - which tend to be more solid. I'd change it to the fa-envelope font-awesome one. ([http://fortawesome.github.io/Font-Awesome/cheatsheet/](http://fortawesome.github.io/Font-Awesome/cheatsheet/))

4. The "how can I help" icon is a bit misleading for me. I'd change it for the "user" (or "group") font-awesome icon. 

5. Currently, the margins to left and right are around 20% each for the content of the page. I'd use something closer to 14% to distribute elements a bit more and use real estate better.

6. On the FAQ session I'd definitely change the hyperlink colors from orange to something else - maybe dark blue - so it brings a clearer contrast with the white background.

Apart from that, most things would be much smaller and cosmetic. I like the working on the home page and the one-page approach a lot :)

**Comment by felixhammerl** [comment]
> The hive background for the home page doesn't provide enough contrast
with the text. Some ways to improve that would be:
> a) Change the background. We can make the hive more transparent so the
background for the text is a bit more solid, for instance. We could also
remove the hive background altogether, but I personally think it's cool to
leave it there to repeat the logo.
> b) Make the text - especially the three clickable items - white instead
of grey.

I guess just try and see what works better

> The three clickable items could call for action more clearly. One
possibility is to have them stand out by having them framed/surrounded with
a solid background - say, round.

Good point.

> The letter icon is in a different style when compared to other icons we
use - which tend to be more solid. I'd change it to the fa-envelope
font-awesome one. (http://fortawesome.github.io/Font-Awesome/cheatsheet/)

It is fontawesome, or more specifically the svg version of font awesome,
but i agree, it seems sort of out of style.

> The "how can I help" icon is a bit misleading for me. I'd change it for
the "user" (or "group") font-awesome icon.

Had that before, thought the heartbeat would get the " give it some love"
across better.

> Currently, the margins to left and right are around 20% each for the
content of the page. I'd use something closer to 14% to distribute elements
a bit more and use real estate better.

By all means, go ahead :)

> On the FAQ session I'd definitely change the hyperlink colors from orange
to something else - maybe dark blue - so it brings a clearer contrast with
the white background.

Sounds good

> Apart from that, most things would be much smaller and cosmetic. I like
the working on the home page and the one-page approach a lot :)

Feel free to change whatever is needed. No strong opinions on the visual
design.

**Comment by albogabriel** [comment]
Thanks, @felixhammerl - we've created a new card (#40) about making the layout/UI changes we've suggested and leave this card specifically for content - all text, information, etc..

**Comment by erikdoe** [comment]
I'll edit the FAQ directly. Some comments on the front page. 

- I'm not sure about that orange bleed effect in the top left corner. 

- At certain width the layout of the "dock" with the social icons doesn't work (see attached). On even narrower screens that completely disappears.

- The switch from the question "Can I try it?" to the login screen of try.pixelated-project.org seems very abrupt. I would suggest either to break the pattern of asking questions and say "try it here" or something, or to add an interstitial page, or to add a bit more text to the login page.

- Most importantly, though, the first sentence doesn't work for me. It's too long, it uses phrases that don't mean anything to me. What is " in-person privacy"? What is the "usefulness of modern email"? Why say "modern crypto" when we use PGP from the 1990-ties? 

- At an absolute minimum we need the tag-line very visible. I also suggest to write "modern email with privacy" and not "modern email with encryption".

![screen shot 2016-02-03 at 18 33 09](https://cloud.githubusercontent.com/assets/954026/12791014/63c7a06e-caa5-11e5-8fe6-78896d7a1ed7.png)

**Comment by felixhammerl** [comment]
> I'll edit the FAQ directly

Thanks!

> - I'm not sure about that orange bleed effect in the top left corner. 

Someone also mentioned that it makes them think their display has a weird malfunction, so no hard feelings if you want it gone. I thought a blip of color might be a nice touch :)

> - At certain width the layout of the "dock" with the social icons doesn't work (see attached).

Woooot. I've tested this in recent FF, Safari and Chrome and I've never seen this behavior. Good catch! Can we reproduce it?

> On even narrower screens that completely disappears.

That is intentional. You wouldn't notice it, because you typically don't resize your screen. On the wider mobile resolutions (phablet in landscape), it should be there.

Should we instead collapse it to a sticky footer when in portrait mode? Does that make sense?

> - The switch from the question "Can I try it?" to the login screen of try.pixelated-project.org seems very abrupt. I would suggest either to break the pattern of asking questions and say "try it here" or something, or to add an interstitial page, or to add a bit more text to the login page.

What would the page look like?
We can also put try.wazokazi.is in an iframe lightbox, same as with the video?

> - Most importantly, though, the first sentence doesn't work for me. It's too long, it uses phrases that don't mean anything to me. What is " in-person privacy"? What is the "usefulness of modern email"? Why say "modern crypto" when we use PGP from the 1990-ties? 
> - At an absolute minimum we need the tag-line very visible. I also suggest to write "modern email with privacy" and not "modern email with encryption".

Fair enough...

What normally happens is the following setup, which I've chosen to forego for now:

Tagline (2 - 5 words)
Value Proposition (more words)

I haven't found a really catchy tagline, and I'm not sure "Modern email with encryption." is catchy enough, either. "Modern email with privacy." might work, though. Maybe we can make a couple of low-tech tests with a bunch of people on the Hacknight.

**Comment by erikdoe** [comment]
I have updated the answers and some questions all the way up the the technical architecture. There are two changes left:

- I didn't update the anchor names in the FAQ because I ran out of time checking where they might be linked from.
- I didn't link to the CI server in the submission answer.

Once these are addressed the FAQ is good to go by me. We can always make tweaks later when it's public.

All in all it's quite long. Maybe we should split out the section on architecture and threat models? But let's do this when the Docker change is done.
